name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          branch: main
          git_remote_url: 'ssh://dokku@patrickdronk.dev:22/movie-ai'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
